### ISSUE TITLE
Which Toon, libcvd, gvars versions

### ISSUE THREAD

**Issue by Markbanfd** [charmie11/PTAMonUbuntu14.04#2]
I'm getting different kind of errors when using the latest TooN and libcvd versions on Ubuntu 14.04. Could you please specify which version have you used for the compilation. 

Thanks,
Mark.

**Comment by charmie11** [comment]
Thanks for this important request!
I'll check it and add detailed information as soon as possible.

**Comment by charmie11** [comment]
The compilation error was caused by the latest TooN.
Use  TooN version 2.0 and don't change Gvars header files, I could compiled TooN, libCVD, and Gvars without any error.
